### ISSUE TITLE
Bug in message text

### ISSUE THREAD

**Issue by ken1000minus7** [harshjohar/fabchat#26]
Message text overflows if the text sent is too long
![image](https://user-images.githubusercontent.com/78747188/216786505-952c95f8-f214-4945-9dcc-4d80e47eed45.png)

**Comment by harshjohar** [comment]
> looks like i didnt give a shit about corner cases while making this project

**Comment by sparsh44** [comment]
sir may i do it?

**Comment by harshjohar** [comment]
alright go ahead
